apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
  namespace: session14
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: web
          image: nginx:1.27-alpine
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-svc
  namespace: session14
spec:
  selector:
    app: inventory
  ports:
    - port: 80
